# Generated by Django 5.2.8 on 2025-11-28 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SMARTPHONE', 'Smartphone'), ('NOTEBOOK', 'Notebook'), ('SMARTTV', 'Smart TV')], max_length=20)),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_minimo', models.IntegerField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('data_operacao', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Especificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensao', models.CharField(max_length=20)),
                ('dimensoes', models.CharField(max_length=50)),
                ('resolucao_tela', models.CharField(max_length=50)),
                ('capacidade_memoria', models.CharField(max_length=50)),
                ('conectividade', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especificacao', to='api.produto')),
            ],
        ),
    ]
