# Generated by Django 5.2.8 on 2025-11-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
